language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "2.7"

env:
  - DJANGO="django>=1.10,<1.11"
  - DJANGO="django>=1.11,<1.12"

branches:
  only:
    - master

# perform static analysis before installing all dependencies
# this allows to save resources and build time if this step fails
before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./runisort; fi

# command to install requirements
install:
  - pip install $DJANGO
  - python setup.py -q develop

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=django_x509 runtests.py

after_success:
  coveralls
