language: python
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

addons:
  apt:
    packages:
      - sqlite3
    sources:
      - travis-ci/sqlite3

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0"

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django>=3.0"

branches:
  only:
    - master

# perform static analysis before installing all dependencies
# this allows to save resources and build time if this step fails
before_install:
  - pip install -U pip setuptools wheel
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint

# command to install requirements
install:
  - pip install $DJANGO
  - python setup.py -q develop

# qa checks
before_script:
  - openwisp-utils-qa-checks --migrations-to-ignore 4 --migration-path ./django_x509/migrations/ --migration-module django_x509

# command to run tests, e.g. python setup.py test
script:
  - jslint django_x509/static/django-x509/js/*.js
  - coverage run --source=django_x509 runtests.py

after_success:
  coveralls
