language: python
dist: focal

python:
  - "3.7"
  - "3.6"

addons:
  apt:
    packages:
      - sqlite3
    sources:
      - travis-ci/sqlite3

env:
  - DJANGO="django~=2.2"
  - DJANGO="django~=3.0"
  - DJANGO="django~=3.1"

branches:
  only:
    - master

# perform static analysis before installing all dependencies
# this allows to save resources and build time if this step fails
before_install:
  - pip install -U pip setuptools wheel
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint

install:
  - pip install $DJANGO
  - python setup.py -q develop
  - pip install --upgrade https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa]

before_script:
  - ./run-qa-checks

script:
  - jslint django_x509/static/django-x509/js/*.js
  - coverage run --source=django_x509 runtests.py
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  coveralls
