language: python
dist: focal

arch:
  - amd64
  - ppc64le

python:
  - "3.7"
  - "3.6"

notifications:
  # will post a summary as comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - sqlite3
    sources:
      - travis-ci/sqlite3

jobs:
  exclude:
    - arch: ppc64le
      python: 3.7
env:
  - DJANGO="django~=2.2"
  - DJANGO="django~=3.0"
  - DJANGO="django~=3.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip setuptools wheel
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  # check is done here to allow travis buddy to include a detailed failure summary
  - ./run-qa-checks
  - coverage run --source=django_x509 runtests.py
  # SAMPLE tests do not influence coverage, so we can speed up tests with --parallel
  - SAMPLE_APP=1 ./runtests.py --parallel --keepdb

after_success:
  coveralls
